baseURL = 'https://liunxcn.gxb.pub/'
languageCode = 'zh-Hans'
title = 'Linux.cn Archive Mirror'
theme = "mainroad"
uglyURLs = true

[Params.logo]
  title = "Linux.cn Archive Mirror"
[Params.sidebar]
  home = "right"
  list = "right"
  single = "right"
  widgets = ["search", "recent", "categories", "taglist", "social", "languages"]
