name: Deploy Hugo

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: "hugo"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.122.0
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: "福建.广西.广东"   
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb          
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: remove unused file for bigger space
        run: |
          sudo rm -rf /usr/share/dotnet \
          sudo rm -rf /opt/ghc \ 
          sudo rm -rf "/usr/local/share/boost" \ 
          sudo rm -rf "$AGENT_TOOLSDIRECTORY" \ 
      - name: Build with Hugo
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
            --gc \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"          
      - name: Deploy to gh-pages
        uses: actions/deploy-pages@v4.0.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: "public"
